const Router = require('express')
const router = new Router()
const catalogueRouter = require('./CatalogueRouter')
const contractsRouter = require('./ContractsRouter')
const contractTransactoinsRouter = require('./ContractTransactoinsRouter')
const ensuranceRequestsRouter = require('./EnsuranceRequestsRouter')
const proposalRouter = require('./ProposalRouter')
const rolesRouter = require('./RolesRouter')
const selectedRouter = require('./SelectedRouter')
const transactionsRouter = require('./TransactionsRouter')
const userRouter = require('./UserRouter')

router.use('/catalogue', catalogueRouter)
router.use('/contracts', contractsRouter)
router.use('/contract-transactoins', contractTransactoinsRouter)
router.use('/ensurance-requests', ensuranceRequestsRouter)
router.use('/proposal', proposalRouter)
router.use('/roles', rolesRouter)
router.use('/selected', selectedRouter)
router.use('/transactions', transactionsRouter)
router.use('/user', userRouter)

module.exports = router
